MORIGINS = [
  "Akroan Jailer",
  "Ampryn Tactician",
  "Anointer of Champions",
  "Archangel of Tithes",
  "Auramancer",
  "Aven Battle Priest",
  "Blessed Spirits",
  "Celestial Flare",
  "Charging Griffin",
  "Cleric of the Forward Order",
  "Consul's Lieutenant",
  "Enlightened Ascetic",
  "Enshrouding Mist",
  "Gideon's Phalanx",
  "Grasp of the Hieromancer",
  "Hallowed Moonlight",
  "Healing Hands",
  "Heavy Infantry",
  "Hixus, Prison Warden",
  "Knight of the Pilgrim's Road",
  "Knight of the White Orchid",
  "Knightly Valor",
  "Kytheon, Hero of Akros",
  "Kytheon's Irregulars",
  "Kytheon's Tactics",
  "Mighty Leap",
  "Murder Investigation",
  "Patron of the Valiant",
  "Relic Seeker",
  "Sentinel of the Eternal Watch",
  "Sigil of the Empty Throne",
  "Stalwart Aven",
  "Starfield of Nyx",
  "Suppression Bonds",
  "Swift Reckoning",
  "Topan Freeblade",
  "Totem-Guide Hartebeest",
  "Tragic Arrogance",
  "Valor in Akros",
  "Vryn Wingmare",
  "War Oracle",
  "Yoked Ox",
  "Alhammarret, High Arbiter",
  "Anchor to the Aether",
  "Artificer's Epiphany",
  "Aspiring Aeronaut",
  "Bone to Ash",
  "Calculated Dismissal",
  "Clash of Wills",
  "Claustrophobia",
  "Day's Undoing",
  "Deep-Sea Terror",
  "Disciple of the Ring",
  "Disperse",
  "Displacement Wave",
  "Dreadwaters",
  "Faerie Miscreant",
  "Harbinger of the Tides",
  "Hydrolash",
  "Jace, Vryn's Prodigy",
  "Jace's Sanctum",
  "Jhessian Thief",
  "Maritime Guard",
  "Mizzium Meddler",
  "Negate",
  "Nivix Barrier",
  "Psychic Rebuttal",
  "Ringwarden Owl",
  "Scrapskin Drake",
  "Screeching Skaab",
  "Send to Sleep",
  "Separatist Voidmage",
  "Sigiled Starfish",
  "Skaab Goliath",
  "Soulblade Djinn",
  "Sphinx's Tutelage",
  "Stratus Walk",
  "Talent of the Telepath",
  "Thopter Spy Network",
  "Tower Geist",
  "Turn to Frog",
  "Watercourser",
  "Whirler Rogue",
  "Willbreaker",
  "Blightcaster",
  "Catacomb Slug",
  "Consecrated by Blood",
  "Cruel Revival",
  "Dark Dabbling",
  "Dark Petition",
  "Deadbridge Shaman",
  "Demonic Pact",
  "Despoiler of Souls",
  "Erebos's Titan",
  "Eyeblight Assassin",
  "Eyeblight Massacre",
  "Fetid Imp",
  "Fleshbag Marauder",
  "Gilt-Leaf Winnower",
  "Gnarlroot Trapper",
  "Graveblade Marauder",
  "Infernal Scarring",
  "Infinite Obliteration",
  "Kothophed, Soul Hoarder",
  "Languish",
  "Liliana, Heretical Healer",
  "Macabre Waltz",
  "Malakir Cullblade",
  "Nantuko Husk",
  "Necromantic Summons",
  "Nightsnare",
  "Priest of the Blood Rite",
  "Rabid Bloodsucker",
  "Read the Bones",
  "Reave Soul",
  "Returned Centaur",
  "Revenant",
  "Shadows of the Past",
  "Shambling Ghoul",
  "Tainted Remedy",
  "Thornbow Archer",
  "Tormented Thoughts",
  "Touch of Moonglove",
  "Undead Servant",
  "Unholy Hunger",
  "Weight of the Underworld",
  "Abbot of Keral Keep",
  "Acolyte of the Inferno",
  "Act of Treason",
  "Akroan Sergeant",
  "Avaricious Dragon",
  "Bellows Lizard",
  "Boggart Brute",
  "Call of the Full Moon",
  "Chandra, Fire of Kaladesh",
  "Chandra's Fury",
  "Chandra's Ignition",
  "Cobblebrute",
  "Demolish",
  "Dragon Fodder",
  "Embermaw Hellion",
  "Enthralling Victor",
  "Exquisite Firecraft",
  "Fiery Conclusion",
  "Fiery Impulse",
  "Firefiend Elemental",
  "Flameshadow Conjuring",
  "Ghirapur Aether Grid",
  "Ghirapur Gearcrafter",
  "Goblin Glory Chaser",
  "Goblin Piledriver",
  "Infectious Bloodlust",
  "Lightning Javelin",
  "Mage-Ring Bully",
  "Magmatic Insight",
  "Molten Vortex",
  "Pia and Kiran Nalaar",
  "Prickleboar",
  "Ravaging Blaze",
  "Scab-Clan Berserker",
  "Seismic Elemental",
  "Skyraker Giant",
  "Smash to Smithereens",
  "Subterranean Scout",
  "Thopter Engineer",
  "Titan's Strength",
  "Volcanic Rambler",
  "Aerial Volley",
  "Animist's Awakening",
  "Caustic Caterpillar",
  "Conclave Naturalists",
  "Dwynen, Gilt-Leaf Daen",
  "Dwynen's Elite",
  "Elemental Bond",
  "Elvish Visionary",
  "Evolutionary Leap",
  "Gaea's Revenge",
  "Gather the Pack",
  "The Great Aurora",
  "Herald of the Pantheon",
  "Hitchclaw Recluse",
  "Honored Hierarch",
  "Joraga Invocation",
  "Leaf Gilder",
  "Llanowar Empath",
  "Managorger Hydra",
  "Mantle of Webs",
  "Might of the Masses",
  "Nissa, Vastwood Seer",
  "Nissa's Pilgrimage",
  "Nissa's Revelation",
  "Orchard Spirit",
  "Outland Colossus",
  "Pharika's Disciple",
  "Reclaim",
  "Rhox Maulers",
  "Skysnare Spider",
  "Somberwald Alpha",
  "Sylvan Messenger",
  "Timberpack Wolf",
  "Titanic Growth",
  "Undercity Troll",
  "Valeron Wardens",
  "Vastwood Gorger",
  "Vine Snare",
  "Wild Instincts",
  "Woodland Bellower",
  "Yeva's Forcemage",
  "Zendikar's Roil",
  "Blazing Hellhound",
  "Blood-Cursed Knight",
  "Bounding Krasis",
  "Citadel Castellan",
  "Iroas's Champion",
  "Possessed Skaab",
  "Reclusive Artificer",
  "Shaman of the Pack",
  "Thunderclap Wyvern",
  "Zendikar Incarnate",
  "Alchemist's Vial",
  "Alhammarret's Archive",
  "Angel's Tomb",
  "Bonded Construct",
  "Brawler's Plate",
  "Chief of the Foundry",
  "Gold-Forged Sentinel",
  "Guardian Automaton",
  "Guardians of Meletis",
  "Hangarback Walker",
  "Helm of the Gods",
  "Jayemdae Tome",
  "Mage-Ring Responder",
  "Meteorite",
  "Orbs of Warding",
  "Prism Ring",
  "Pyromancer's Goggles",
  "Ramroller",
  "Runed Servitor",
  "Sigil of Valor",
  "Sword of the Animist",
  "Throwing Knife",
  "Veteran's Sidearm",
  "War Horn",
  "Battlefield Forge",
  "Caves of Koilos",
  "Evolving Wilds",
  "Foundry of the Consuls",
  "Llanowar Wastes",
  "Mage-Ring Network",
  "Rogue's Passage",
  "Shivan Reef",
  "Yavimaya Coast",
  "Plains",
  "Island",
  "Swamp",
  "Mountain",
  "Forest",
  "Aegis Angel",
  "Divine Verdict",
  "Eagle of the Watch",
  "Serra Angel",
  "Into the Void",
  "Mahamoti Djinn",
  "Weave Fate",
  "Flesh to Dust",
  "Mind Rot",
  "Nightmare",
  "Sengir Vampire",
  "Plummet",
  "Prized Unicorn",
  "Terra Stomper"]

DRAGONS =["Scion of Ugin",
          "Anafenza, Kin-Tree Spirit",
          "Arashin Foremost",
          "Artful Maneuver",
          "Aven Sunstriker",
          "Aven Tactician",
          "Battle Mastery",
          "Center Soul",
          "Champion of Arashin",
          "Dragon Hunter",
          "Dragon's Eye Sentry",
          "Dromoka Captain",
          "Dromoka Dunecaster",
          "Dromoka Warrior",
          "Echoes of the Kin Tree",
          "Enduring Victory",
          "Fate Forgotten",
          "Glaring Aegis",
          "Gleam of Authority",
          "Graceblade Artisan",
          "Great Teacher's Decree",
          "Herald of Dromoka",
          "Hidden Dragonslayer",
          "Lightwalker",
          "Misthoof Kirin",
          "Myth Realized",
          "Ojutai Exemplars",
          "Orator of Ojutai",
          "Pacifism",
          "Profound Journey",
          "Radiant Purge",
          "Resupply",
          "Sandcrafter Mage",
          "Sandstorm Charger",
          "Scale Blessing",
          "Secure the Wastes",
          "Shieldhide Dragon",
          "Silkwrap",
          "Strongarm Monk",
          "Student of Ojutai",
          "Sunscorch Regent",
          "Surge of Righteousness",
          "Territorial Roc",
          "Ancient Carp",
          "Anticipate",
          "Belltoll Dragon",
          "Blessed Reincarnation",
          "Clone Legion",
          "Contradict",
          "Dance of the Skywise",
          "Dirgur Nemesis",
          "Dragonlord's Prerogative",
          "Elusive Spellfist",
          "Encase in Ice",
          "Glint",
          "Gudul Lurker",
          "Gurmag Drowner",
          "Icefall Regent",
          "Illusory Gains",
          "Learn from the Past",
          "Living Lore",
          "Mirror Mockery",
          "Monastery Loremaster",
          "Mystic Meditation",
          "Negate",
          "Ojutai Interceptor",
          "Ojutai's Breath",
          "Ojutai's Summons",
          "Palace Familiar",
          "Profaner of the Dead",
          "Qarsi Deceiver",
          "Reduce in Stature",
          "Shorecrasher Elemental",
          "Sidisi's Faithful",
          "Sight Beyond Sight",
          "Silumgar Sorcerer",
          "Silumgar Spell-Eater",
          "Silumgar's Scorn",
          "Skywise Teachings",
          "Stratus Dancer",
          "Taigam's Strike",
          "Updraft Elemental",
          "Void Squall",
          "Youthful Scholar",
          "Zephyr Scribe",
          "Acid-Spewer Dragon",
          "Ambuscade Shaman",
          "Blood-Chin Fanatic",
          "Blood-Chin Rager",
          "Butcher's Glee",
          "Coat with Venom",
          "Corpseweft",
          "Damnable Pact",
          "Deadly Wanderings",
          "Death Wind",
          "Deathbringer Regent",
          "Defeat",
          "Duress",
          "Dutiful Attendant",
          "Flatten",
          "Foul Renewal",
          "Foul-Tongue Invocation",
          "Foul-Tongue Shriek",
          "Gravepurge",
          "Hand of Silumgar",
          "Hedonist's Trove",
          "Kolaghan Skirmisher",
          "Marang River Skeleton",
          "Marsh Hulk",
          "Mind Rot",
          "Minister of Pain",
          "Pitiless Horde",
          "Qarsi Sadist",
          "Rakshasa Gravecaller",
          "Reckless Imp",
          "Risen Executioner",
          "Self-Inflicted Wound",
          "Shambling Goblin",
          "Sibsig Icebreakers",
          "Sidisi, Undead Vizier",
          "Silumgar Assassin",
          "Silumgar Butcher",
          "Ukud Cobra",
          "Ultimate Price",
          "Virulent Plague",
          "Vulturous Aven",
          "Wandering Tombshell",
          "Atarka Efreet",
          "Atarka Pummeler",
          "Berserkers' Onslaught",
          "Commune with Lava",
          "Crater Elemental",
          "Descent of the Dragons",
          "Draconic Roar",
          "Dragon Fodder",
          "Dragon Tempest",
          "Dragon Whisperer",
          "Dragonlord's Servant",
          "Hardened Berserker",
          "Impact Tremors",
          "Ire Shaman",
          "Kindled Fury",
          "Kolaghan Aspirant",
          "Kolaghan Forerunners",
          "Kolaghan Stormsinger",
          "Lightning Berserker",
          "Lose Calm",
          "Magmatic Chasm",
          "Qal Sisma Behemoth",
          "Rending Volley",
          "Roast",
          "Sabertooth Outrider",
          "Sarkhan's Rage",
          "Sarkhan's Triumph",
          "Screamreach Brawler",
          "Seismic Rupture",
          "Sprinting Warbrute",
          "Stormcrag Elemental",
          "Stormwing Dragon",
          "Summit Prowler",
          "Tail Slash",
          "Thunderbreak Regent",
          "Tormenting Voice",
          "Twin Bolt",
          "Vandalize",
          "Volcanic Rush",
          "Volcanic Vision",
          "Warbringer",
          "Zurgo Bellstriker",
          "Aerie Bowmasters",
          "Ainok Artillerist",
          "Ainok Survivalist",
          "Assault Formation",
          "Atarka Beastbreaker",
          "Avatar of the Resolute",
          "Circle of Elders",
          "Collected Company",
          "Colossodon Yearling",
          "Conifer Strider",
          "Deathmist Raptor",
          "Den Protector",
          "Display of Dominance",
          "Dragon-Scarred Bear",
          "Dromoka's Gift",
          "Epic Confrontation",
          "Explosive Vegetation",
          "Foe-Razer Regent",
          "Glade Watcher",
          "Guardian Shield-Bearer",
          "Herdchaser Dragon",
          "Inspiring Call",
          "Lurking Arynx",
          "Naturalize",
          "Obscuring Aether",
          "Pinion Feast",
          "Press the Advantage",
          "Revealing Wind",
          "Salt Road Ambushers",
          "Salt Road Quartermasters",
          "Sandsteppe Scavenger",
          "Scaleguard Sentinels",
          "Segmented Krotiq",
          "Servant of the Scale",
          "Shaman of Forgotten Ways",
          "Shape the Sands",
          "Sheltered Aerie",
          "Sight of the Scalelords",
          "Stampeding Elk Herd",
          "Sunbringer's Touch",
          "Surrak, the Hunt Caller",
          "Tread Upon",
          "Arashin Sovereign",
          "Atarka's Command",
          "Boltwing Marauder",
          "Cunning Breezedancer",
          "Dragonlord Atarka",
          "Dragonlord Dromoka",
          "Dragonlord Kolaghan",
          "Dragonlord Ojutai",
          "Dragonlord Silumgar",
          "Dromoka's Command",
          "Enduring Scalelord",
          "Harbinger of the Hunt",
          "Kolaghan's Command",
          "Narset Transcendent",
          "Necromaster Dragon",
          "Ojutai's Command",
          "Pristine Skywise",
          "Ruthless Deathfang",
          "Sarkhan Unbroken",
          "Savage Ventmaw",
          "Silumgar's Command",
          "Swift Warkite",
          "Ancestral Statue",
          "Atarka Monument",
          "Custodian of the Trove",
          "Dragonloft Idol",
          "Dromoka Monument",
          "Gate Smasher",
          "Keeper of the Lens",
          "Kolaghan Monument",
          "Ojutai Monument",
          "Silumgar Monument",
          "Spidersilk Net",
          "Stormrider Rig",
          "Tapestry of the Ages",
          "Vial of Dragonfire",
          "Evolving Wilds",
          "Haven of the Spirit Dragon"]

FATE = ["Ugin, the Spirit Dragon",
        "Abzan Advantage",
        "Abzan Runemark",
        "Abzan Skycaptain",
        "Arashin Cleric",
        "Aven Skirmisher",
        "Channel Harm",
        "Citadel Siege",
        "Daghatar the Adamant",
        "Dragon Bell Monk",
        "Dragonscale General",
        "Elite Scaleguard",
        "Great-Horn Krushok",
        "Honor's Reward",
        "Jeskai Barricade",
        "Lightform",
        "Lotus-Eye Mystics",
        "Mardu Woe-Reaper",
        "Mastery of the Unseen",
        "Monastery Mentor",
        "Pressure Point",
        "Rally the Ancestors",
        "Sage's Reverie",
        "Sandblast",
        "Sandsteppe Outcast",
        "Soul Summons",
        "Soulfire Grand Master",
        "Valorous Stance",
        "Wandering Champion",
        "Wardscale Dragon",
        "Aven Surveyor",
        "Cloudform",
        "Enhanced Awareness",
        "Fascination",
        "Frost Walker",
        "Jeskai Infiltrator",
        "Jeskai Runemark",
        "Jeskai Sage",
        "Lotus Path Djinn",
        "Marang River Prowler",
        "Mindscour Dragon",
        "Mistfire Adept",
        "Monastery Siege",
        "Neutralizing Blast",
        "Rakshasa's Disdain",
        "Reality Shift",
        "Refocus",
        "Renowned Weaponsmith",
        "Rite of Undoing",
        "Sage-Eye Avengers",
        "Shifting Loyalties",
        "Shu Yun, the Silent Tempest",
        "Sultai Skullkeeper",
        "Supplant Form",
        "Temporal Trespass",
        "Torrent Elemental",
        "Whisk Away",
        "Will of the Naga",
        "Write into Being",
        "Alesha's Vanguard",
        "Ancestral Vengeance",
        "Archfiend of Depravity",
        "Battle Brawler",
        "Brutal Hordechief",
        "Crux of Fate",
        "Dark Deal",
        "Diplomacy of the Wastes",
        "Douse in Gloom",
        "Fearsome Awakening",
        "Ghastly Conscription",
        "Grave Strength",
        "Gurmag Angler",
        "Hooded Assassin",
        "Mardu Shadowspear",
        "Mardu Strike Leader",
        "Merciless Executioner",
        "Noxious Dragon",
        "Orc Sureshot",
        "Palace Siege",
        "Qarsi High Priest",
        "Reach of Shadows",
        "Sibsig Host",
        "Sibsig Muckdraggers",
        "Soulflayer",
        "Sultai Emissary",
        "Sultai Runemark",
        "Tasigur, the Golden Fang",
        "Tasigur's Cruelty",
        "Typhoid Rats",
        "Alesha, Who Smiles at Death",
        "Arcbond",
        "Bathe in Dragonfire",
        "Bloodfire Enforcers",
        "Break Through the Line",
        "Collateral Damage",
        "Defiant Ogre",
        "Dragonrage",
        "Fierce Invocation",
        "Flamerush Rider",
        "Flamewake Phoenix",
        "Friendly Fire",
        "Goblin Heelcutter",
        "Gore Swine",
        "Humble Defector",
        "Hungering Yeti",
        "Lightning Shrieker",
        "Mardu Runemark",
        "Mardu Scout",
        "Mob Rule",
        "Outpost Siege",
        "Pyrotechnics",
        "Rageform",
        "Shaman of the Great Hunt",
        "Shockmaw Dragon",
        "Smoldering Efreet",
        "Temur Battle Rage",
        "Vaultbreaker",
        "Wild Slash",
        "Abzan Beastmaster",
        "Abzan Kin-Guard",
        "Ainok Guide",
        "Ambush Krotiq",
        "Arashin War Beast",
        "Archers of Qarsi",
        "Battlefront Krushok",
        "Cached Defenses",
        "Destructor Dragon",
        "Feral Krushok",
        "Formless Nurturing",
        "Frontier Mastodon",
        "Frontier Siege",
        "Fruit of the First Tree",
        "Hunt the Weak",
        "Map the Wastes",
        "Return to the Earth",
        "Ruthless Instincts",
        "Sandsteppe Mastodon",
        "Shamanic Revelation",
        "Sudden Reclamation",
        "Temur Runemark",
        "Temur Sabertooth",
        "Temur War Shaman",
        "Warden of the First Tree",
        "Whisperer of the Wilds",
        "Whisperwood Elemental",
        "Wildcall",
        "Winds of Qal Sisma",
        "Yasova Dragonclaw",
        "Atarka, World Render",
        "Cunning Strike",
        "Dromoka, the Eternal",
        "Ethereal Ambush",
        "Grim Contest",
        "Harsh Sustenance",
        "Kolaghan, the Storm's Fury",
        "Ojutai, Soul of Winter",
        "Silumgar, the Drifting Death",
        "War Flare",
        "Goblin Boom Keg",
        "Hero's Blade",
        "Hewed Stone Retainers",
        "Pilgrim of the Fires",
        "Scroll of the Masters",
        "Ugin's Construct",
        "Bloodfell Caves",
        "Blossoming Sands",
        "Crucible of the Spirit Dragon",
        "Dismal Backwater",
        "Jungle Hollow",
        "Rugged Highlands",
        "Scoured Barrens",
        "Swiftwater Cliffs",
        "Thornwood Falls",
        "Tranquil Cove",
        "Wind-Scarred Crag"]

KHANS = ["Abzan Battle Priest",
         "Abzan Falconer",
         "Ainok Bond-Kin",
         "Alabaster Kirin",
         "Brave the Sands",
         "Dazzling Ramparts",
         "Defiant Strike",
         "End Hostilities",
         "Erase",
         "Feat of Resistance",
         "Firehoof Cavalry",
         "Herald of Anafenza",
         "High Sentinels of Arashin",
         "Jeskai Student",
         "Kill Shot",
         "Mardu Hateblade",
         "Mardu Hordechief",
         "Master of Pearls",
         "Rush of Battle",
         "Sage-Eye Harrier",
         "Salt Road Patrol",
         "Seeker of the Way",
         "Siegecraft",
         "Smite the Monstrous",
         "Suspension Field",
         "Take Up Arms",
         "Timely Hordemate",
         "Venerable Lammasu",
         "War Behemoth",
         "Watcher of the Roost",
         "Wingmate Roc",
         "Blinding Spray",
         "Cancel",
         "Clever Impersonator",
         "Crippling Chill",
         "Dig Through Time",
         "Disdainful Stroke",
         "Dragon's Eye Savants",
         "Embodiment of Spring",
         "Force Away",
         "Glacial Stalker",
         "Icy Blast",
         "Jeskai Elder",
         "Jeskai Windscout",
         "Kheru Spellsnatcher",
         "Mistfire Weaver",
         "Monastery Flock",
         "Mystic of the Hidden Way",
         "Pearl Lake Ancient",
         "Quiet Contemplation",
         "Riverwheel Aerialists",
         "Scaldkin",
         "Scion of Glaciers",
         "Set Adrift",
         "Singing Bell Strike",
         "Stubborn Denial",
         "Taigam's Scheming",
         "Thousand Winds",
         "Treasure Cruise",
         "Waterwhirl",
         "Weave Fate",
         "Wetland Sambar",
         "Whirlwind Adept",
         "Bellowing Saddlebrute",
         "Bitter Revelation",
         "Bloodsoaked Champion",
         "Dead Drop",
         "Debilitating Injury",
         "Despise",
         "Disowned Ancestor",
         "Dutiful Return",
         "Empty the Pits",
         "Grim Haruspex",
         "Gurmag Swiftwing",
         "Kheru Bloodsucker",
         "Kheru Dreadmaw",
         "Krumar Bond-Kin",
         "Mardu Skullhunter",
         "Mer-Ek Nightblade",
         "Molting Snakeskin",
         "Murderous Cut",
         "Necropolis Fiend",
         "Raiders' Spoils",
         "Rakshasa's Secret",
         "Retribution of the Ancients",
         "Rite of the Serpent",
         "Rotting Mastodon",
         "Ruthless Ripper",
         "Shambling Attendants",
         "Sidisi's Pet",
         "Sultai Scavenger",
         "Swarm of Bloodflies",
         "Throttle",
         "Unyielding Krumar",
         "Act of Treason",
         "Ainok Tracker",
         "Arc Lightning",
         "Arrow Storm",
         "Ashcloud Phoenix",
         "Barrage of Boulders",
         "Bloodfire Expert",
         "Bloodfire Mentor",
         "Bring Low",
         "Burn Away",
         "Canyon Lurkers",
         "Crater's Claws",
         "Dragon Grip",
         "Dragon-Style Twins",
         "Goblinslide",
         "Horde Ambusher",
         "Hordeling Outburst",
         "Howl of the Horde",
         "Jeering Instigator",
         "Leaping Master",
         "Mardu Blazebringer",
         "Mardu Heart-Piercer",
         "Mardu Warshrieker",
         "Monastery Swiftspear",
         "Sarkhan, the Dragonspeaker",
         "Shatter",
         "Summit Prowler",
         "Swift Kick",
         "Tormenting Voice",
         "Trumpet Blast",
         "Valley Dasher",
         "War-Name Aspirant",
         "Alpine Grizzly",
         "Archers' Parapet",
         "Awaken the Bear",
         "Become Immense",
         "Dragonscale Boon",
         "Feed the Clan",
         "Hardened Scales",
         "Heir of the Wilds",
         "Highland Game",
         "Hooded Hydra",
         "Hooting Mandrills",
         "Incremental Growth",
         "Kin-Tree Warden",
         "Longshot Squad",
         "Meandering Towershell",
         "Naturalize",
         "Pine Walker",
         "Rattleclaw Mystic",
         "Roar of Challenge",
         "Sagu Archer",
         "Savage Punch",
         "Scout the Borders",
         "See the Unwritten",
         "Seek the Horizon",
         "Smoke Teller",
         "Sultai Flayer",
         "Temur Charger",
         "Trail of Mystery",
         "Tusked Colossodon",
         "Tuskguard Captain",
         "Windstorm",
         "Woolly Loxodon",
         "Abomination of Gudul",
         "Abzan Ascendancy",
         "Abzan Charm",
         "Abzan Guide",
         "Anafenza, the Foremost",
         "Ankle Shanker",
         "Armament Corps",
         "Avalanche Tusker",
         "Bear's Companion",
         "Butcher of the Horde",
         "Chief of the Edge",
         "Chief of the Scale",
         "Crackling Doom",
         "Death Frenzy",
         "Deflecting Palm",
         "Duneblast",
         "Efreet Weaponmaster",
         "Flying Crane Technique",
         "Highspire Mantis",
         "Icefeather Aven",
         "Ivorytusk Fortress",
         "Jeskai Ascendancy",
         "Jeskai Charm",
         "Kheru Lich Lord",
         "Kin-Tree Invocation",
         "Mantis Rider",
         "Mardu Ascendancy",
         "Mardu Charm",
         "Mardu Roughrider",
         "Master the Way",
         "Mindswipe",
         "Narset, Enlightened Master",
         "Ponyback Brigade",
         "Rakshasa Deathdealer",
         "Rakshasa Vizier",
         "Ride Down",
         "Sage of the Inward Eye",
         "Sagu Mauler",
         "Savage Knuckleblade",
         "Secret Plans",
         "Sidisi, Brood Tyrant",
         "Siege Rhino",
         "Snowhorn Rider",
         "Sorin, Solemn Visitor",
         "Sultai Ascendancy",
         "Sultai Charm",
         "Sultai Soothsayer",
         "Surrak Dragonclaw",
         "Temur Ascendancy",
         "Temur Charm",
         "Trap Essence",
         "Utter End",
         "Villainous Wealth",
         "Warden of the Eye",
         "Winterflame",
         "Zurgo Helmsmasher",
         "Abzan Banner",
         "Altar of the Brood",
         "Briber's Purse",
         "Cranial Archive",
         "Dragon Throne of Tarkir",
         "Ghostfire Blade",
         "Heart-Piercer Bow",
         "Jeskai Banner",
         "Lens of Clarity",
         "Mardu Banner",
         "Sultai Banner",
         "Temur Banner",
         "Ugin's Nexus",
         "Witness of the Ages",
         "Bloodfell Caves",
         "Bloodstained Mire",
         "Blossoming Sands",
         "Dismal Backwater",
         "Flooded Strand",
         "Frontier Bivouac",
         "Jungle Hollow",
         "Mystic Monastery",
         "Nomad Outpost",
         "Opulent Palace",
         "Polluted Delta",
         "Rugged Highlands",
         "Sandsteppe Citadel",
         "Scoured Barrens",
         "Swiftwater Cliffs",
         "Thornwood Falls",
         "Tomb of the Spirit Dragon",
         "Tranquil Cove",
         "Wind-Scarred Crag",
         "Windswept Heath",
         "Wooded Foothills"]

M15 = ["Ajani Steadfast",
       "Ajani's Pridemate",
       "Avacyn, Guardian Angel",
       "Battle Mastery",
       "Boonweaver Giant",
       "Congregate",
       "Constricting Sliver",
       "Dauntless River Marshal",
       "Devouring Light",
       "Divine Favor",
       "Ephemeral Shields",
       "First Response",
       "Geist of the Moors",
       "Heliod's Pilgrim",
       "Hushwing Gryff",
       "Kinsbaile Skirmisher",
       "Marked by Honor",
       "Mass Calcify",
       "Meditation Puzzle",
       "Midnight Guard",
       "Oppressive Rays",
       "Oreskos Swiftclaw",
       "Paragon of New Dawns",
       "Pillar of Light",
       "Preeminent Captain",
       "Raise the Alarm",
       "Razorfoot Griffin",
       "Resolute Archangel",
       "Return to the Ranks",
       "Sanctified Charge",
       "Selfless Cathar",
       "Seraph of the Masses",
       "Solemn Offering",
       "Soul of Theros",
       "Soulmender",
       "Spectra Ward",
       "Spirit Bonds",
       "Sungrace Pegasus",
       "Tireless Missionaries",
       "Triplicate Spirits",
       "Wall of Essence",
       "Warden of the Beyond",
       "Aeronaut Tinkerer",
       "Aetherspouts",
       "Amphin Pathmage",
       "Chasm Skulker",
       "Chief Engineer",
       "Chronostutter",
       "Coral Barrier",
       "Diffusion Sliver",
       "Dissipate",
       "Divination",
       "Encrust",
       "Ensoul Artifact",
       "Frost Lynx",
       "Fugitive Wizard",
       "Glacial Crasher",
       "Hydrosurge",
       "Illusory Angel",
       "Into the Void",
       "Invisibility",
       "Jace, the Living Guildpact",
       "Jace's Ingenuity",
       "Jalira, Master Polymorphist",
       "Jorubai Murk Lurker",
       "Kapsho Kitefins",
       "Master of Predicaments",
       "Mercurial Pretender",
       "Military Intelligence",
       "Mind Sculpt",
       "Negate",
       "Nimbus of the Isles",
       "Paragon of Gathering Mists",
       "Peel from Reality",
       "Polymorphist's Jest",
       "Quickling",
       "Research Assistant",
       "Soul of Ravnica",
       "Statute of Denial",
       "Stormtide Leviathan",
       "Turn to Frog",
       "Void Snare",
       "Wall of Frost",
       "Welkin Tern",
       "Accursed Spirit",
       "Black Cat",
       "Blood Host",
       "Carrion Crow",
       "Caustic Tar",
       "Child of Night",
       "Covenant of Blood",
       "Crippling Blight",
       "Cruel Sadist",
       "Endless Obedience",
       "Eternal Thirst",
       "Feast on the Fallen",
       "Festergloom",
       "Flesh to Dust",
       "Gravedigger",
       "In Garruk's Wake",
       "Indulgent Tormentor",
       "Leeching Sliver",
       "Liliana Vess",
       "Mind Rot",
       "Necrobite",
       "Necrogen Scudder",
       "Necromancer's Assistant",
       "Necromancer's Stockpile",
       "Nightfire Giant",
       "Ob Nixilis, Unshackled",
       "Paragon of Open Graves",
       "Rotfeaster Maggot",
       "Shadowcloak Vampire",
       "Sign in Blood",
       "Soul of Innistrad",
       "Stab Wound",
       "Stain the Mind",
       "Typhoid Rats",
       "Ulcerate",
       "Unmake the Graves",
       "Wall of Limbs",
       "Waste Not",
       "Witch's Familiar",
       "Xathrid Slyblade",
       "Zof Shade",
       "Act on Impulse",
       "Aggressive Mining",
       "Altac Bloodseeker",
       "Belligerent Sliver",
       "Blastfire Bolt",
       "Borderland Marauder",
       "Brood Keeper",
       "Burning Anger",
       "Chandra, Pyromaster",
       "Circle of Flame",
       "Clear a Path",
       "Cone of Flame",
       "Crowd's Favor",
       "Crucible of Fire",
       "Forge Devil",
       "Foundry Street Denizen",
       "Frenzied Goblin",
       "Generator Servant",
       "Goblin Kaboomist",
       "Goblin Rabblemaster",
       "Goblin Roughrider",
       "Hammerhand",
       "Heat Ray",
       "Hoarding Dragon",
       "Inferno Fist",
       "Kird Chieftain",
       "Krenko's Enforcer",
       "Kurkesh, Onakke Ancient",
       "Lava Axe",
       "Lightning Strike",
       "Might Makes Right",
       "Miner's Bane",
       "Paragon of Fierce Defiance",
       "Rummaging Goblin",
       "Scrapyard Mongrel",
       "Shrapnel Blast",
       "Siege Dragon",
       "Soul of Shandalar",
       "Stoke the Flames",
       "Thundering Giant",
       "Torch Fiend",
       "Wall of Fire",
       "Ancient Silverback",
       "Back to Nature",
       "Carnivorous Moss-Beast",
       "Charging Rhino",
       "Chord of Calling",
       "Elvish Mystic",
       "Feral Incarnation",
       "Gather Courage",
       "Genesis Hydra",
       "Hornet Nest",
       "Hornet Queen",
       "Hunt the Weak",
       "Hunter's Ambush",
       "Invasive Species",
       "Kalonian Twingrove",
       "Life's Legacy",
       "Living Totem",
       "Naturalize",
       "Netcaster Spider",
       "Nissa, Worldwaker",
       "Nissa's Expedition",
       "Overwhelm",
       "Paragon of Eternal Wilds",
       "Phytotitan",
       "Plummet",
       "Ranger's Guile",
       "Reclamation Sage",
       "Restock",
       "Roaring Primadox",
       "Runeclaw Bear",
       "Satyr Wayfinder",
       "Shaman of Spring",
       "Siege Wurm",
       "Soul of Zendikar",
       "Sunblade Elf",
       "Titanic Growth",
       "Undergrowth Scavenger",
       "Venom Sliver",
       "Verdant Haven",
       "Vineweft",
       "Wall of Mulch",
       "Yisan, the Wanderer Bard",
       "Garruk, Apex Predator",
       "Sliver Hivelord",
       "Avarice Amulet",
       "Brawler's Plate",
       "Bronze Sable",
       "The Chain Veil",
       "Gargoyle Sentinel",
       "Grindclock",
       "Haunted Plate Mail",
       "Hot Soup",
       "Juggernaut",
       "Meteorite",
       "Obelisk of Urd",
       "Ornithopter",
       "Perilous Vault",
       "Phyrexian Revoker",
       "Profane Memento",
       "Rogue's Gloves",
       "Sacred Armory",
       "Scuttling Doom Engine",
       "Shield of the Avatar",
       "Soul of New Phyrexia",
       "Staff of the Death Magus",
       "Staff of the Flame Magus",
       "Staff of the Mind Magus",
       "Staff of the Sun Magus",
       "Staff of the Wild Magus",
       "Tormod's Crypt",
       "Tyrant's Machine",
       "Will-Forged Golem",
       "Battlefield Forge",
       "Caves of Koilos",
       "Darksteel Citadel",
       "Evolving Wilds",
       "Llanowar Wastes",
       "Radiant Fountain",
       "Shivan Reef",
       "Sliver Hive",
       "Urborg, Tomb of Yawgmoth",
       "Yavimaya Coast",
       "Divine Verdict",
       "Inspired Charge",
       "Serra Angel",
       "Mahamoti Djinn",
       "Nightmare",
       "Sengir Vampire",
       "Furnace Whelp",
       "Seismic Strike",
       "Shivan Dragon",
       "Centaur Courser",
       "Garruk's Packleader",
       "Terra Stomper"]

JOURNEY = ["Aegis of the Gods",
           "Ajani's Presence",
           "Akroan Mastiff",
           "Armament of Nyx",
           "Banishing Light",
           "Dawnbringer Charioteers",
           "Deicide",
           "Dictate of Heliod",
           "Eagle of the Watch",
           "Eidolon of Rhetoric",
           "Font of Vigor",
           "Godsend",
           "Harvestguard Alseids",
           "Lagonna-Band Trailblazer",
           "Launch the Fleet",
           "Leonin Iconoclast",
           "Mortal Obstinacy",
           "Nyx-Fleece Ram",
           "Oppressive Rays",
           "Oreskos Swiftclaw",
           "Phalanx Formation",
           "Quarry Colossus",
           "Reprisal",
           "Sightless Brawler",
           "Skybind",
           "Skyspear Cavalry",
           "Stonewise Fortifier",
           "Supply-Line Cranes",
           "Tethmos High Priest",
           "Aerial Formation",
           "Battlefield Thaumaturge",
           "Cloaked Siren",
           "Countermand",
           "Crystalline Nautilus",
           "Dakra Mystic",
           "Daring Thief",
           "Dictate of Kruphix",
           "Font of Fortunes",
           "Godhunter Octopus",
           "Hour of Need",
           "Hubris",
           "Hypnotic Siren",
           "Interpret the Signs",
           "Kiora's Dismissal",
           "Pin to the Earth",
           "Polymorphous Rush",
           "Pull from the Deep",
           "Riptide Chimera",
           "Rise of Eagles",
           "Sage of Hours",
           "Scourge of Fleets",
           "Sigiled Starfish",
           "Thassa's Devourer",
           "Thassa's Ire",
           "Triton Cavalry",
           "Triton Shorestalker",
           "War-Wing Siren",
           "Whitewater Naiads",
           "Agent of Erebos",
           "Aspect of Gorgon",
           "Bloodcrazed Hoplite",
           "Brain Maggot",
           "Cast into Darkness",
           "Cruel Feeding",
           "Dictate of Erebos",
           "Doomwake Giant",
           "Dreadbringer Lampads",
           "Extinguish All Hope",
           "Feast of Dreams",
           "Felhide Petrifier",
           "Font of Return",
           "Gnarled Scarhide",
           "Grim Guardian",
           "King Macar, the Gold-Cursed",
           "Master of the Feast",
           "Nightmarish End",
           "Nyx Infusion",
           "Pharika's Chosen",
           "Returned Reveler",
           "Ritual of the Returned",
           "Rotted Hulk",
           "Silence the Believers",
           "Spiteful Blow",
           "Squelching Leeches",
           "Thoughtrender Lamia",
           "Tormented Thoughts",
           "Worst Fears",
           "Akroan Line Breaker",
           "Bearer of the Heavens",
           "Bladetusk Boar",
           "Blinding Flare",
           "Cyclops of Eternal Fury",
           "Dictate of the Twin Gods",
           "Eidolon of the Great Revel",
           "Flamespeaker's Will",
           "Flurry of Horns",
           "Font of Ire",
           "Forgeborn Oreads",
           "Gluttonous Cyclops",
           "Harness by Force",
           "Knowledge and Power",
           "Lightning Diadem",
           "Magma Spray",
           "Mogis's Warhound",
           "Pensive Minotaur",
           "Prophetic Flamespeaker",
           "Riddle of Lightning",
           "Rollick of Abandon",
           "Rouse the Mob",
           "Satyr Hoplite",
           "Sigiled Skink",
           "Spawn of Thraxes",
           "Spite of Mogis",
           "Starfall",
           "Twinflame",
           "Wildfire Cerberus",
           "Bassara Tower Archer",
           "Colossal Heroics",
           "Consign to Dust",
           "Desecration Plague",
           "Dictate of Karametra",
           "Eidolon of Blossoms",
           "Font of Fertility",
           "Golden Hind",
           "Goldenhide Ox",
           "Heroes' Bane",
           "Humbler of Mortals",
           "Hydra Broodmaster",
           "Kruphix's Insight",
           "Market Festival",
           "Nature's Panoply",
           "Nessian Game Warden",
           "Oakheart Dryads",
           "Pheres-Band Thunderhoof",
           "Pheres-Band Warchief",
           "Ravenous Leucrocota",
           "Renowned Weaver",
           "Reviving Melody",
           "Satyr Grovedancer",
           "Setessan Tactics",
           "Solidarity of Heroes",
           "Spirespine",
           "Strength from the Fallen",
           "Swarmborn Giant",
           "Ajani, Mentor of Heroes",
           "Athreos, God of Passage",
           "Desperate Stand",
           "Disciple of Deceit",
           "Fleetfeather Cockatrice",
           "Iroas, God of Victory",
           "Keranos, God of Storms",
           "Kruphix, God of Horizons",
           "Nyx Weaver",
           "Pharika, God of Affliction",
           "Revel of the Fallen God",
           "Stormchaser Chimera",
           "Underworld Coinsmith",
           "Armory of Iroas",
           "Chariot of Victory",
           "Deserter's Quarters",
           "Gold-Forged Sentinel",
           "Hall of Triumph",
           "Mana Confluence",
           "Temple of Epiphany",
           "Temple of Malady"]

BORN = ["Acolyte's Reward",
        "Akroan Phalanx",
        "Akroan Skyguard",
        "Archetype of Courage",
        "Brimaz, King of Oreskos",
        "Dawn to Dusk",
        "Eidolon of Countless Battles",
        "Elite Skirmisher",
        "Ephara's Radiance",
        "Excoriate",
        "Fated Retribution",
        "Ghostblade Eidolon",
        "Glimpse the Sun God",
        "God-Favored General",
        "Great Hart",
        "Griffin Dreamfinder",
        "Hero of Iroas",
        "Hold at Bay",
        "Loyal Pegasus",
        "Mortal's Ardor",
        "Nyxborn Shieldmate",
        "Oreskos Sun Guide",
        "Ornitharch",
        "Plea for Guidance",
        "Revoke Existence",
        "Silent Sentinel",
        "Spirit of the Labyrinth",
        "Sunbond",
        "Vanguard of Brimaz",
        "Aerie Worshippers",
        "Arbiter of the Ideal",
        "Archetype of Imagination",
        "Chorus of the Tides",
        "Crypsis",
        "Deepwater Hypnotist",
        "Divination",
        "Eternity Snare",
        "Evanescent Intellect",
        "Fated Infatuation",
        "Flitterstep Eidolon",
        "Floodtide Serpent",
        "Kraken of the Straits",
        "Meletis Astronomer",
        "Mindreaver",
        "Nullify",
        "Nyxborn Triton",
        "Oracle's Insight",
        "Perplexing Chimera",
        "Retraction Helix",
        "Siren of the Fanged Coast",
        "Sphinx's Disciple",
        "Stratus Walk",
        "Sudden Storm",
        "Thassa's Rebuff",
        "Tromokratis",
        "Vortex Elemental",
        "Whelming Wave",
        "Archetype of Finality",
        "Ashiok's Adept",
        "Asphyxiate",
        "Bile Blight",
        "Black Oak of Odunos",
        "Champion of Stray Souls",
        "Claim of Erebos",
        "Drown in Sorrow",
        "Eater of Hope",
        "Eye Gouge",
        "Fate Unraveler",
        "Fated Return",
        "Felhide Brawler",
        "Forlorn Pseudamma",
        "Forsaken Drifters",
        "Gild",
        "Grisly Transformation",
        "Herald of Torment",
        "Marshmist Titan",
        "Necrobite",
        "Nyxborn Eidolon",
        "Odunos River Trawler",
        "Pain Seer",
        "Sanguimancy",
        "Servant of Tymaret",
        "Shrike Harpy",
        "Spiteful Returned",
        "Warchanter of Mogis",
        "Weight of the Underworld",
        "Akroan Conscriptor",
        "Archetype of Aggression",
        "Bolt of Keranos",
        "Cyclops of One-Eyed Pass",
        "Epiphany Storm",
        "Everflame Eidolon",
        "Fall of the Hammer",
        "Fated Conflagration",
        "Fearsome Temper",
        "Felhide Spiritbinder",
        "Flame-Wreathed Phoenix",
        "Forgestoker Dragon",
        "Impetuous Sunchaser",
        "Kragma Butcher",
        "Lightning Volley",
        "Nyxborn Rollicker",
        "Oracle of Bones",
        "Pharagax Giant",
        "Pinnacle of Rage",
        "Reckless Reveler",
        "Rise to the Challenge",
        "Satyr Firedancer",
        "Satyr Nyx-Smith",
        "Scouring Sands",
        "Searing Blood",
        "Stormcaller of Keranos",
        "Thunder Brute",
        "Thunderous Might",
        "Whims of the Fates",
        "Archetype of Endurance",
        "Aspect of Hydra",
        "Charging Badger",
        "Courser of Kruphix",
        "Culling Mark",
        "Fated Intervention",
        "Graverobber Spider",
        "Hero of Leina Tower",
        "Hunter's Prowess",
        "Karametra's Favor",
        "Mischief and Mayhem",
        "Mortal's Resolve",
        "Nessian Demolok",
        "Nessian Wilds Ravager",
        "Noble Quarry",
        "Nyxborn Wolf",
        "Peregrination",
        "Pheres-Band Raiders",
        "Pheres-Band Tromper",
        "Raised by Wolves",
        "Satyr Wayfinder",
        "Scourge of Skola Vale",
        "Setessan Oathsworn",
        "Setessan Starbreaker",
        "Skyreaping",
        "Snake of the Golden Grove",
        "Swordwise Centaur",
        "Unravel the Aether",
        "Chromanticore",
        "Ephara, God of the Polis",
        "Ephara's Enlightenment",
        "Fanatic of Xenagos",
        "Karametra, God of Harvests",
        "Kiora, the Crashing Wave",
        "Kiora's Follower",
        "Mogis, God of Slaughter",
        "Phenax, God of Deception",
        "Ragemonger",
        "Reap What Is Sown",
        "Siren of the Silent Song",
        "Xenagos, God of Revels",
        "Astral Cornucopia",
        "Gorgon's Head",
        "Heroes' Podium",
        "Pillar of War",
        "Siren Song Lyre",
        "Springleaf Drum",
        "Temple of Enlightenment",
        "Temple of Malice",
        "Temple of Plenty"]

THEROS = ["Battlewise Valor",
          "Cavalry Pegasus",
          "Celestial Archon",
          "Chained to the Rocks",
          "Chosen by Heliod",
          "Dauntless Onslaught",
          "Decorated Griffin",
          "Divine Verdict",
          "Elspeth, Sun's Champion",
          "Ephara's Warden",
          "Evangel of Heliod",
          "Fabled Hero",
          "Favored Hoplite",
          "Gift of Immortality",
          "Glare of Heresy",
          "Gods Willing",
          "Heliod, God of the Sun",
          "Heliod's Emissary",
          "Hopeful Eidolon",
          "Hundred-Handed One",
          "Lagonna-Band Elder",
          "Last Breath",
          "Leonin Snarecaster",
          "Observant Alseid",
          "Ordeal of Heliod",
          "Phalanx Leader",
          "Ray of Dissolution",
          "Scholar of Athreos",
          "Setessan Battle Priest",
          "Setessan Griffin",
          "Silent Artisan",
          "Soldier of the Pantheon",
          "Spear of Heliod",
          "Traveling Philosopher",
          "Vanquish the Foul",
          "Wingsteed Rider",
          "Yoked Ox",
          "Annul",
          "Aqueous Form",
          "Artisan of Forms",
          "Benthic Giant",
          "Bident of Thassa",
          "Breaching Hippocamp",
          "Coastline Chimera",
          "Crackling Triton",
          "Curse of the Swine",
          "Dissolve",
          "Fate Foretold",
          "Gainsay",
          "Griptide",
          "Horizon Scholar",
          "Lost in a Labyrinth",
          "Master of Waves",
          "Meletis Charlatan",
          "Mnemonic Wall",
          "Nimbus Naiad",
          "Omenspeaker",
          "Ordeal of Thassa",
          "Prescient Chimera",
          "Prognostic Sphinx",
          "Sea God's Revenge",
          "Sealock Monster",
          "Shipbreaker Kraken",
          "Stymied Hopes",
          "Swan Song",
          "Thassa, God of the Sea",
          "Thassa's Bounty",
          "Thassa's Emissary",
          "Triton Fortune Hunter",
          "Triton Shorethief",
          "Triton Tactics",
          "Vaporkin",
          "Voyage's End",
          "Wavecrash Triton",
          "Abhorrent Overlord",
          "Agent of the Fates",
          "Asphodel Wanderer",
          "Baleful Eidolon",
          "Blood-Toll Harpy",
          "Boon of Erebos",
          "Cavern Lampad",
          "Cutthroat Maneuver",
          "Dark Betrayal",
          "Disciple of Phenax",
          "Erebos, God of the Dead",
          "Erebos's Emissary",
          "Felhide Minotaur",
          "Fleshmad Steed",
          "Gray Merchant of Asphodel",
          "Hero's Downfall",
          "Hythonia the Cruel",
          "Insatiable Harpy",
          "Keepsake Gorgon",
          "Lash of the Whip",
          "Loathsome Catoblepas",
          "March of the Returned",
          "Mogis's Marauder",
          "Nighthowler",
          "Ordeal of Erebos",
          "Pharika's Cure",
          "Read the Bones",
          "Rescue from the Underworld",
          "Returned Centaur",
          "Returned Phalanx",
          "Scourgemark",
          "Sip of Hemlock",
          "Thoughtseize",
          "Tormented Hero",
          "Viper's Kiss",
          "Whip of Erebos",
          "Akroan Crusader",
          "Anger of the Gods",
          "Arena Athlete",
          "Borderland Minotaur",
          "Boulderfall",
          "Coordinated Assault",
          "Deathbellow Raider",
          "Demolish",
          "Dragon Mantle",
          "Ember Swallower",
          "Fanatic of Mogis",
          "Firedrinker Satyr",
          "Flamespeaker Adept",
          "Hammer of Purphoros",
          "Ill-Tempered Cyclops",
          "Labyrinth Champion",
          "Lightning Strike",
          "Magma Jet",
          "Messenger's Speed",
          "Minotaur Skullcleaver",
          "Ordeal of Purphoros",
          "Peak Eruption",
          "Portent of Betrayal",
          "Priest of Iroas",
          "Purphoros, God of the Forge",
          "Purphoros's Emissary",
          "Rage of Purphoros",
          "Rageblood Shaman",
          "Satyr Rambler",
          "Spark Jolt",
          "Spearpoint Oread",
          "Stoneshock Giant",
          "Stormbreath Dragon",
          "Titan of Eternal Fire",
          "Titan's Strength",
          "Two-Headed Cerberus",
          "Wild Celebrants",
          "Agent of Horizons",
          "Anthousa, Setessan Hero",
          "Arbor Colossus",
          "Artisan's Sorrow",
          "Boon Satyr",
          "Bow of Nylea",
          "Centaur Battlemaster",
          "Commune with the Gods",
          "Defend the Hearth",
          "Fade into Antiquity",
          "Feral Invocation",
          "Hunt the Hunter",
          "Karametra's Acolyte",
          "Leafcrown Dryad",
          "Mistcutter Hydra",
          "Nemesis of Mortals",
          "Nessian Asp",
          "Nessian Courser",
          "Nylea, God of the Hunt",
          "Nylea's Disciple",
          "Nylea's Emissary",
          "Nylea's Presence",
          "Ordeal of Nylea",
          "Pheres-Band Centaurs",
          "Polukranos, World Eater",
          "Reverent Hunter",
          "Satyr Hedonist",
          "Satyr Piper",
          "Savage Surge",
          "Sedge Scorpion",
          "Shredding Winds",
          "Staunch-Hearted Warrior",
          "Sylvan Caryatid",
          "Time to Feed",
          "Voyaging Satyr",
          "Vulpine Goliath",
          "Warriors' Lesson",
          "Akroan Hoplite",
          "Anax and Cymede",
          "Ashen Rider",
          "Ashiok, Nightmare Weaver",
          "Battlewise Hoplite",
          "Chronicler of Heroes",
          "Daxos of Meletis",
          "Destructive Revelry",
          "Fleecemane Lion",
          "Horizon Chimera",
          "Kragma Warcaller",
          "Medomai the Ageless",
          "Pharika's Mender",
          "Polis Crusher",
          "Prophet of Kruphix",
          "Psychic Intrusion",
          "Reaper of the Wilds",
          "Sentry of the Underworld",
          "Shipwreck Singer",
          "Spellheart Chimera",
          "Steam Augury",
          "Triad of Fates",
          "Tymaret, the Murder King",
          "Underworld Cerberus",
          "Xenagos, the Reveler",
          "Akroan Horse",
          "Anvilwrought Raptor",
          "Bronze Sable",
          "Burnished Hart",
          "Colossus of Akros",
          "Flamecast Wheel",
          "Fleetfeather Sandals",
          "Guardians of Meletis",
          "Opaline Unicorn",
          "Prowler's Helm",
          "Pyxis of Pandemonium",
          "Traveler's Amulet",
          "Witches' Eye",
          "Nykthos, Shrine to Nyx",
          "Temple of Abandon",
          "Temple of Deceit",
          "Temple of Mystery",
          "Temple of Silence",
          "Temple of Triumph",
          "Unknown Shores"]



